id: P542155E2
initial_creation_type: input
source_metadata:
  title: Nāradasmṛti
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Dharma -- Smṛti
  data entry: Yasuke Ikari
  contribution to GRETIL: Yasuke Ikari
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:29:01.731951'
last_modified_at: '2022-03-09T15:29:01.731969'
